<a href="https://colab.research.google.com/github/mostafaelmehi/milestone-2/blob/main/the%20update%20to%20work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Introduction**
This project aims to analyze customer behavior at Starbucks using survey data to achieve the following goals:

Improve menu offerings by identifying popular items and customer preferences.
Target specific customer segments based on demographics and spending patterns.
Reduce food waste by understanding purchasing habits and infrequent item purchases.
The dataset consists of 122 survey responses collected in Malaysia. By leveraging a structured data analysis process, the project seeks to provide actionable insights to enhance customer satisfaction and optimize operations.
https://www.kaggle.com/datasets/mahirahmzh/starbucks-customer-retention-malaysia-survey?select=Starbucks+satisfactory+survey.csv

**2. Comparable Datasets and Analyses**:

Similar datasets and analyses include:
**Sub Sandwich Customer Satisfaction Score**
This dataset offers a comprehensive look at customer satisfaction levels across various sub sandwich brands. It delves into the nitty-gritty of what makes a sub sandwich experience delightful, covering a wide array of factors such as food quality, service efficiency, ambiance, and overall customer sentiment.
https://www.kaggle.com/datasets/kane6543/sub-sandwich-customer-satisfaction-score


**Canteen Shop Transaction Data**

https://www.kaggle.com/datasets/susanta21/canteen-shop-transaction-data

**Pizza Restaurant Sales**

https://www.kaggle.com/datasets/shilongzhuang/pizza-sales

**3. Methodology**

The CRISP-DM (Cross-Industry Standard Process for Data Mining) framework guides this project:

Business Understanding:

Define project objectives, including improving menu offerings, targeting customer segments, and reducing waste.

Data Understanding:

Explore survey data to identify key patterns in customer behavior.

Data Preparation:

Clean, preprocess, and engineer features from survey responses.

Analysis:

Perform initial data summaries, meta-analyses, and visualizations to derive actionable insights.

**4. Data Acquisition**

Source: The dataset is a customer satisfaction survey collected from Starbucks customers in Malaysia.

Attributes:
Demographics: Age, gender, income.
Behavior: Visit frequency, spending habits, and preferences.
Ratings: Quality, service, and ambiance.
Initial Cleaning:
Removed unnecessary columns (meeting_hangout_likelihood, nearest_outlet).
Addressed inconsistencies in categorical data (e.g., enjoy_method, frequent_purchase).

Handled null values by removing incomplete rows

**5. Initial Data Analysis / Data Summary**
- Renaming Column Names
- General Dataset Overview:
df.info()
print(df.describe())
- Demographics Analysis:
using the function .valuecounts()
the goal is
Understand the Dataset:

1.Provide an overview of the structure, types of data, and completeness of the dataset.
Identify potential issues (e.g., missing values or imbalanced categories) and address them if needed.
Identify Key Patterns and Trends:

2.Summarize demographics (e.g., age, gender) to understand the customer base.
Highlight purchasing behaviors (e.g., spending habits, visit frequency) to identify customer preferences and habits.

3.Extract Actionable Insights:

Use the summarized data to support the project's goals, such as:
Improving menu offerings by identifying popular items.
Targeting specific customer segments based on demographics or spending patterns.

4.Highlighting areas for operational improvements (e.g., service quality or membership engagement).
Set the Foundation for Further Analysis:

Ensure a clear understanding of the dataset before proceeding to advanced steps, like data visualization or deeper meta-analysis.

**6. Preliminary Suggestions / Pseudo-Code for Data Preprocessing**
Standardizing Data:

Standardized inconsistent text entries
df = df.apply(lambda col: col.str.strip().str.lower() if col.dtypes == 'object' else col)

Encoding Categorical Variables:
df['annual_income'] = df.annual_income.map(
    {
        'less than rm25,000':1,
        'rm25,000 - rm50,000':2,
        'rm50,000 - rm100,000':3,
        'rm100,000 - rm150,000':4,
        'more than rm150,000':5,
    }

**7. Challenges for Further Project Development**
Key Challenges:

Data Limitations:

Small dataset size (122 entries) limits generalizability and statistical robustness.
Region-specific data may not apply to global Starbucks operations.
Behavioral Data Bias:

Survey responses may reflect intentions (e.g., continue_buying) rather than actual behavior.
Feature Engineering:

Balancing subjective weights for derived features like loyalty and spending potential.

Visualizations and Interpretability:

Effectively presenting findings to address business goals while managing high-dimensional data is crucial.
Ethical Concerns:

Ensuring compliance with privacy laws and responsible use of customer data

- Read the Data using Pandas and convert it to a DataFrame.
- Overview of columns, data types, and non-null values.
- Preview the first 5 rows to better understand the data.

In [105]:
import pandas as pd
df = pd.read_csv('/content/sample_data/Starbucks satisfactory survey.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 21 columns):
 #   Column                                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                                  --------------  -----
 0   Timestamp                                                                                                               122 non-null    object
 1   1. Your Gender                                                                                                          122 non-null    object
 2   2. Your Age                                                                                                             122 non-null    object
 3   3. Are you currently....?                                                                                               122 non-null    object
 4   4. What is your annual income?                                                                                          122 non-null    object
 5   5. How often do you visit Starbucks?                                                                                    122 non-null    object
 6   6. How do you usually enjoy Starbucks?                                                                                  121 non-null    object
 7   7. How much time do you normally  spend during your visit?                                                              122 non-null    object
 8   8. The nearest Starbucks's outlet to you is...?                                                                         122 non-null    object
 9   9. Do you have Starbucks membership card?                                                                               122 non-null    object
 10  10. What do you most frequently purchase at Starbucks?                                                                  122 non-null    object
 11  11. On average, how much would you spend at Starbucks per visit?                                                        122 non-null    object
 12  12. How would you rate the quality of Starbucks compared to other brands (Coffee Bean, Old Town White Coffee..) to be:  122 non-null    int64
 13  13. How would you rate the price range at Starbucks?                                                                    122 non-null    int64
 14  14. How important are sales and promotions in your purchase decision?                                                   122 non-null    int64
 15  15. How would you rate the ambiance at Starbucks? (lighting, music, etc...)                                             122 non-null    int64
 16  16. You rate the WiFi quality at Starbucks as..                                                                         122 non-null    int64
 17  17. How would you rate the service at Starbucks? (Promptness, friendliness, etc..)                                      122 non-null    int64
 18  18. How likely you will choose Starbucks for doing business meetings or hangout with friends?                           122 non-null    int64
 19  19. How do you come to hear of promotions at Starbucks? Check all that apply.                                           121 non-null    object
 20  20. Will you continue buying at Starbucks?                                                                              122 non-null    object
dtypes: int64(7), object(14)
memory usage: 20.1+ KB

,Timestamp,1. Your Gender,2. Your Age,3. Are you currently....?,4. What is your annual income?,5. How often do you visit Starbucks?,6. How do you usually enjoy Starbucks?,7. How much time do you normally spend during your visit?,8. The nearest Starbucks's outlet to you is...?,9. Do you have Starbucks membership card?,...,"11. On average, how much would you spend at Starbucks per visit?","12. How would you rate the quality of Starbucks compared to other brands (Coffee Bean, Old Town White Coffee..) to be:",13. How would you rate the price range at Starbucks?,14. How important are sales and promotions in your purchase decision?,"15. How would you rate the ambiance at Starbucks? (lighting, music, etc...)",16. You rate the WiFi quality at Starbucks as..,"17. How would you rate the service at Starbucks? (Promptness, friendliness, etc..)",18. How likely you will choose Starbucks for doing business meetings or hangout with friends?,19. How do you come to hear of promotions at Starbucks? Check all that apply.,20. Will you continue buying at Starbucks?
0,2019/10/01 12:38:43 PM GMT+8,Female,From 20 to 29,Student,"Less than RM25,000",Rarely,Dine in,Between 30 minutes to 1 hour,within 1km,Yes,...,Less than RM20,4,3,5,5,4,4,3,Starbucks Website/Apps;Social Media;Emails;Dea...,Yes
1,2019/10/01 12:38:54 PM GMT+8,Female,From 20 to 29,Student,"Less than RM25,000",Rarely,Take away,Below 30 minutes,1km - 3km,Yes,...,Less than RM20,4,3,4,4,4,5,2,Social Media;In Store displays,Yes
2,2019/10/01 12:38:56 PM GMT+8,Male,From 20 to 29,Employed,"Less than RM25,000",Monthly,Dine in,Between 30 minutes to 1 hour,more than 3km,Yes,...,Less than RM20,4,3,4,4,4,4,3,In Store displays;Billboards,Yes
3,2019/10/01 12:39:08 PM GMT+8,Female,From 20 to 29,Student,"Less than RM25,000",Rarely,Take away,Below 30 minutes,more than 3km,No,...,Less than RM20,2,1,4,3,3,3,3,Through friends and word of mouth,No
4,2019/10/01 12:39:20 PM GMT+8,Male,From 20 to 29,Student,"Less than RM25,000",Monthly,Take away,Between 30 minutes to 1 hour,1km - 3km,No,...,Around RM20 - RM40,3,3,4,2,2,3,3,Starbucks Website/Apps;Social Media,Yes

Shortened and more readable column names

In [106]:
new_column_names = {
    "Timestamp": "timestamp",
    "1. Your Gender": "gender",
    "2. Your Age": "age",
    "3. Are you currently....?": "current_status",
    "4. What is your annual income?": "annual_income",
    "5. How often do you visit Starbucks?": "visit_frequency",
    "6. How do you usually enjoy Starbucks?": "enjoy_method",
    "7. How much time do you normally  spend during your visit?": "visit_duration",
    "8. The nearest Starbucks's outlet to you is...?": "nearest_outlet",
    "9. Do you have Starbucks membership card?": "membership_card",
    "10. What do you most frequently purchase at Starbucks?": "frequent_purchase",
    "11. On average, how much would you spend at Starbucks per visit?": "spend_per_visit",
    "12. How would you rate the quality of Starbucks compared to other brands (Coffee Bean, Old Town White Coffee..) to be:": "quality_rating",
    "13. How would you rate the price range at Starbucks?": "price_rating",
    "14. How important are sales and promotions in your purchase decision?": "sales_importance",
    "15. How would you rate the ambiance at Starbucks? (lighting, music, etc...)": "ambiance_rating",
    "16. You rate the WiFi quality at Starbucks as..": "wifi_rating",
    "17. How would you rate the service at Starbucks? (Promptness, friendliness, etc..)": "service_rating",
    "18. How likely you will choose Starbucks for doing business meetings or hangout with friends?": "meeting_hangout_likelihood",
    "19. How do you come to hear of promotions at Starbucks? Check all that apply.": "promotion_source",
    "20. Will you continue buying at Starbucks?": "continue_buying"
}

# Assuming `df` is your DataFrame
df.rename(columns = new_column_names, inplace = True)

# Display the updated column names
print(df.columns)
df.head()

Index(['timestamp', 'gender', 'age', 'current_status', 'annual_income',
       'visit_frequency', 'enjoy_method', 'visit_duration', 'nearest_outlet',
       'membership_card', 'frequent_purchase', 'spend_per_visit',
       'quality_rating', 'price_rating', 'sales_importance', 'ambiance_rating',
       'wifi_rating', 'service_rating', 'meeting_hangout_likelihood',
       'promotion_source', 'continue_buying'],
      dtype='object')

,timestamp,gender,age,current_status,annual_income,visit_frequency,enjoy_method,visit_duration,nearest_outlet,membership_card,...,spend_per_visit,quality_rating,price_rating,sales_importance,ambiance_rating,wifi_rating,service_rating,meeting_hangout_likelihood,promotion_source,continue_buying
0,2019/10/01 12:38:43 PM GMT+8,Female,From 20 to 29,Student,"Less than RM25,000",Rarely,Dine in,Between 30 minutes to 1 hour,within 1km,Yes,...,Less than RM20,4,3,5,5,4,4,3,Starbucks Website/Apps;Social Media;Emails;Dea...,Yes
1,2019/10/01 12:38:54 PM GMT+8,Female,From 20 to 29,Student,"Less than RM25,000",Rarely,Take away,Below 30 minutes,1km - 3km,Yes,...,Less than RM20,4,3,4,4,4,5,2,Social Media;In Store displays,Yes
2,2019/10/01 12:38:56 PM GMT+8,Male,From 20 to 29,Employed,"Less than RM25,000",Monthly,Dine in,Between 30 minutes to 1 hour,more than 3km,Yes,...,Less than RM20,4,3,4,4,4,4,3,In Store displays;Billboards,Yes
3,2019/10/01 12:39:08 PM GMT+8,Female,From 20 to 29,Student,"Less than RM25,000",Rarely,Take away,Below 30 minutes,more than 3km,No,...,Less than RM20,2,1,4,3,3,3,3,Through friends and word of mouth,No
4,2019/10/01 12:39:20 PM GMT+8,Male,From 20 to 29,Student,"Less than RM25,000",Monthly,Take away,Between 30 minutes to 1 hour,1km - 3km,No,...,Around RM20 - RM40,3,3,4,2,2,3,3,Starbucks Website/Apps;Social Media,Yes

Counts the total number of duplicate rows in the DataFrame

In [107]:
print(df.duplicated().sum())

0

Check for missing Null values in the data

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   timestamp                   122 non-null    object
 1   gender                      122 non-null    object
 2   age                         122 non-null    object
 3   current_status              122 non-null    object
 4   annual_income               122 non-null    object
 5   visit_frequency             122 non-null    object
 6   enjoy_method                121 non-null    object
 7   visit_duration              122 non-null    object
 8   nearest_outlet              122 non-null    object
 9   membership_card             122 non-null    object
 10  frequent_purchase           122 non-null    object
 11  spend_per_visit             122 non-null    object
 12  quality_rating              122 non-null    int64
 13  price_rating                122 non-null    int64
 14  sales_importance            122 non-null    int64
 15  ambiance_rating             122 non-null    int64
 16  wifi_rating                 122 non-null    int64
 17  service_rating              122 non-null    int64
 18  meeting_hangout_likelihood  122 non-null    int64
 19  promotion_source            121 non-null    object
 20  continue_buying             122 non-null    object
dtypes: int64(7), object(14)
memory usage: 20.1+ KB

removing null values

In [109]:
print(df.isnull().sum())

timestamp                     0
gender                        0
age                           0
current_status                0
annual_income                 0
visit_frequency               0
enjoy_method                  1
visit_duration                0
nearest_outlet                0
membership_card               0
frequent_purchase             0
spend_per_visit               0
quality_rating                0
price_rating                  0
sales_importance              0
ambiance_rating               0
wifi_rating                   0
service_rating                0
meeting_hangout_likelihood    0
promotion_source              1
continue_buying               0
dtype: int64

In [110]:
df.dropna(inplace=True)

Check for missing null values ​​in data after update

In [111]:
print(df.isnull().sum())

timestamp                     0
gender                        0
age                           0
current_status                0
annual_income                 0
visit_frequency               0
enjoy_method                  0
visit_duration                0
nearest_outlet                0
membership_card               0
frequent_purchase             0
spend_per_visit               0
quality_rating                0
price_rating                  0
sales_importance              0
ambiance_rating               0
wifi_rating                   0
service_rating                0
meeting_hangout_likelihood    0
promotion_source              0
continue_buying               0
dtype: int64

Delete the columns ('nearest_outlet', 'meeting_hangout_likelihood',timestamp and wifi_rating ) because they are not useful in the analysis.

In [112]:
df.drop(columns = ['nearest_outlet', 'meeting_hangout_likelihood','timestamp','wifi_rating'], inplace = True)

In [113]:
df.head()

,gender,age,current_status,annual_income,visit_frequency,enjoy_method,visit_duration,membership_card,frequent_purchase,spend_per_visit,quality_rating,price_rating,sales_importance,ambiance_rating,service_rating,promotion_source,continue_buying
0,Female,From 20 to 29,Student,"Less than RM25,000",Rarely,Dine in,Between 30 minutes to 1 hour,Yes,Coffee,Less than RM20,4,3,5,5,4,Starbucks Website/Apps;Social Media;Emails;Dea...,Yes
1,Female,From 20 to 29,Student,"Less than RM25,000",Rarely,Take away,Below 30 minutes,Yes,Cold drinks;Pastries,Less than RM20,4,3,4,4,5,Social Media;In Store displays,Yes
2,Male,From 20 to 29,Employed,"Less than RM25,000",Monthly,Dine in,Between 30 minutes to 1 hour,Yes,Coffee,Less than RM20,4,3,4,4,4,In Store displays;Billboards,Yes
3,Female,From 20 to 29,Student,"Less than RM25,000",Rarely,Take away,Below 30 minutes,No,Coffee,Less than RM20,2,1,4,3,3,Through friends and word of mouth,No
4,Male,From 20 to 29,Student,"Less than RM25,000",Monthly,Take away,Between 30 minutes to 1 hour,No,Coffee;Sandwiches,Around RM20 - RM40,3,3,4,2,3,Starbucks Website/Apps;Social Media,Yes

Create a new column 'Customer_ID'

In [114]:
df['Customer_ID'] = df.index + 1

# Move 'Customer_ID' to the first position
df.insert(0, 'Customer_ID', df.pop('Customer_ID'))

In [115]:
df.head()

,Customer_ID,gender,age,current_status,annual_income,visit_frequency,enjoy_method,visit_duration,membership_card,frequent_purchase,spend_per_visit,quality_rating,price_rating,sales_importance,ambiance_rating,service_rating,promotion_source,continue_buying
0,1,Female,From 20 to 29,Student,"Less than RM25,000",Rarely,Dine in,Between 30 minutes to 1 hour,Yes,Coffee,Less than RM20,4,3,5,5,4,Starbucks Website/Apps;Social Media;Emails;Dea...,Yes
1,2,Female,From 20 to 29,Student,"Less than RM25,000",Rarely,Take away,Below 30 minutes,Yes,Cold drinks;Pastries,Less than RM20,4,3,4,4,5,Social Media;In Store displays,Yes
2,3,Male,From 20 to 29,Employed,"Less than RM25,000",Monthly,Dine in,Between 30 minutes to 1 hour,Yes,Coffee,Less than RM20,4,3,4,4,4,In Store displays;Billboards,Yes
3,4,Female,From 20 to 29,Student,"Less than RM25,000",Rarely,Take away,Below 30 minutes,No,Coffee,Less than RM20,2,1,4,3,3,Through friends and word of mouth,No
4,5,Male,From 20 to 29,Student,"Less than RM25,000",Monthly,Take away,Between 30 minutes to 1 hour,No,Coffee;Sandwiches,Around RM20 - RM40,3,3,4,2,3,Starbucks Website/Apps;Social Media,Yes

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 121 entries, 0 to 121
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        121 non-null    int64
 1   gender             121 non-null    object
 2   age                121 non-null    object
 3   current_status     121 non-null    object
 4   annual_income      121 non-null    object
 5   visit_frequency    121 non-null    object
 6   enjoy_method       121 non-null    object
 7   visit_duration     121 non-null    object
 8   membership_card    121 non-null    object
 9   frequent_purchase  121 non-null    object
 10  spend_per_visit    121 non-null    object
 11  quality_rating     121 non-null    int64
 12  price_rating       121 non-null    int64
 13  sales_importance   121 non-null    int64
 14  ambiance_rating    121 non-null    int64
 15  service_rating     121 non-null    int64
 16  promotion_source   121 non-null    object
 17  continue_buying    121 non-null    object
dtypes: int64(6), object(12)
memory usage: 18.0+ KB

Clean all text columns in the DataFrame:
- Remove extra spaces from the beginning and end of the text (strip)
- Convert text to lowercase for standardization

In [117]:
df = df.apply(lambda col: col.str.strip().str.lower() if col.dtypes == 'object' else col)

df.head()

,Customer_ID,gender,age,current_status,annual_income,visit_frequency,enjoy_method,visit_duration,membership_card,frequent_purchase,spend_per_visit,quality_rating,price_rating,sales_importance,ambiance_rating,service_rating,promotion_source,continue_buying
0,1,female,from 20 to 29,student,"less than rm25,000",rarely,dine in,between 30 minutes to 1 hour,yes,coffee,less than rm20,4,3,5,5,4,starbucks website/apps;social media;emails;dea...,yes
1,2,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,yes,cold drinks;pastries,less than rm20,4,3,4,4,5,social media;in store displays,yes
2,3,male,from 20 to 29,employed,"less than rm25,000",monthly,dine in,between 30 minutes to 1 hour,yes,coffee,less than rm20,4,3,4,4,4,in store displays;billboards,yes
3,4,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,no,coffee,less than rm20,2,1,4,3,3,through friends and word of mouth,no
4,5,male,from 20 to 29,student,"less than rm25,000",monthly,take away,between 30 minutes to 1 hour,no,coffee;sandwiches,around rm20 - rm40,3,3,4,2,3,starbucks website/apps;social media,yes

Count the occurrences of each unique value in the 'frequent_purchase' column

In [118]:
df.frequent_purchase.value_counts()

frequent_purchase
coffee                                           65
cold drinks                                      25
coffee;pastries                                   6
coffee;cold drinks                                6
coffee;sandwiches                                 3
pastries                                          2
never                                             2
cold drinks;juices;pastries                       2
coffee;pastries;sandwiches                        1
cold drinks;pastries                              1
coffee;cold drinks;pastries;sandwiches            1
coffee;juices;pastries;sandwiches                 1
jaws chip                                         1
cake                                              1
cold drinks;pastries;sandwiches                   1
cold drinks;never                                 1
nothing                                           1
coffee;cold drinks;juices;pastries;sandwiches     1
Name: count, dtype: int64

- Splitting the composite attributes into lists
- Here, I'm splitting the 'frequent_purchase' column into separate items using the delimiter ';'.
- This will allow me to work with each individual item separately.

In [119]:
split_items = df['frequent_purchase'].str.split(';')
print("\n Split 'frequent_purchase' into lists:")
split_items.head()

 Split 'frequent_purchase' into lists:

0                   [coffee]
1    [cold drinks, pastries]
2                   [coffee]
3                   [coffee]
4       [coffee, sandwiches]
Name: frequent_purchase, dtype: object

- Extracting unique items from the lists
- To create individual columns for each item, I first need to find all unique items in the 'frequent_purchase' data.
- I initialize an empty list called unique_items and populate it by iterating through each list in split_items.
- If an item is not already in unique_items, I add it. This ensures no duplicates in the final list.

In [120]:
unique_items = []
for sublist in split_items:
    for item in sublist:
        if item not in unique_items:
            unique_items.append(item)

print("\n Unique items extracted from 'frequent_purchase':")
print(unique_items)

 Unique items extracted from 'frequent_purchase':
['coffee', 'cold drinks', 'pastries', 'sandwiches', 'juices', 'never', 'jaws chip', 'cake', 'nothing']

- Creating new columns for each unique item
- Now that I have all unique items, I create a new column for each one in the DataFrame.
- 1. For each unique item, I check if it exists in the 'frequent_purchase' column for a given row.
- 2. If the item exists, I assign a value of 1 to the new column; otherwise, I assign 0.

In [121]:
for item in unique_items:
    df[item] = df['frequent_purchase'].apply(lambda x: 1 if item in x else 0)

df.drop(columns=['frequent_purchase'],inplace=True)
print("\n DataFrame with new columns for each unique item:")
df.head()

 DataFrame with new columns for each unique item:

,Customer_ID,gender,age,current_status,annual_income,visit_frequency,enjoy_method,visit_duration,membership_card,spend_per_visit,...,continue_buying,coffee,cold drinks,pastries,sandwiches,juices,never,jaws chip,cake,nothing
0,1,female,from 20 to 29,student,"less than rm25,000",rarely,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,yes,1,0,0,0,0,0,0,0,0
1,2,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,yes,less than rm20,...,yes,0,1,1,0,0,0,0,0,0
2,3,male,from 20 to 29,employed,"less than rm25,000",monthly,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,yes,1,0,0,0,0,0,0,0,0
3,4,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,no,less than rm20,...,no,1,0,0,0,0,0,0,0,0
4,5,male,from 20 to 29,student,"less than rm25,000",monthly,take away,between 30 minutes to 1 hour,no,around rm20 - rm40,...,yes,1,0,0,1,0,0,0,0,0

Merge some columns together to create a new column for easy analysis.

In [122]:
# Combine the 'never' and 'nothing' columns into one column called 'never'
df['never'] = df['never'] + df['nothing']
# Combine the 'sandwiches' and 'jaws chip' columns into one column called 'Purchased_Food'
df["Purchased_Food"] = df['sandwiches'] | df["jaws chip"]
# Combine the 'pastries' and 'cake' columns into one column called 'Purchased_pastries'
df["Purchased_pastries"] = df['pastries'] | df["cake"]
# Drop the original 'nothing' column
df.drop(columns=['nothing', 'cake', 'pastries', 'jaws chip', 'sandwiches'], inplace=True)
df.head()

,Customer_ID,gender,age,current_status,annual_income,visit_frequency,enjoy_method,visit_duration,membership_card,spend_per_visit,...,ambiance_rating,service_rating,promotion_source,continue_buying,coffee,cold drinks,juices,never,Purchased_Food,Purchased_pastries
0,1,female,from 20 to 29,student,"less than rm25,000",rarely,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,5,4,starbucks website/apps;social media;emails;dea...,yes,1,0,0,0,0,0
1,2,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,yes,less than rm20,...,4,5,social media;in store displays,yes,0,1,0,0,0,1
2,3,male,from 20 to 29,employed,"less than rm25,000",monthly,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,4,4,in store displays;billboards,yes,1,0,0,0,0,0
3,4,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,no,less than rm20,...,3,3,through friends and word of mouth,no,1,0,0,0,0,0
4,5,male,from 20 to 29,student,"less than rm25,000",monthly,take away,between 30 minutes to 1 hour,no,around rm20 - rm40,...,2,3,starbucks website/apps;social media,yes,1,0,0,0,1,0

\دا ليه؟؟

---


Add a new column 'total_purchased' as the sum of 'Purchased_Food' and 'Purchased_pastries'

In [123]:
df['total_purchased'] = df[['Purchased_Food', 'Purchased_pastries']].sum(axis=1)

df.head()

,Customer_ID,gender,age,current_status,annual_income,visit_frequency,enjoy_method,visit_duration,membership_card,spend_per_visit,...,service_rating,promotion_source,continue_buying,coffee,cold drinks,juices,never,Purchased_Food,Purchased_pastries,total_purchased
0,1,female,from 20 to 29,student,"less than rm25,000",rarely,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,4,starbucks website/apps;social media;emails;dea...,yes,1,0,0,0,0,0,0
1,2,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,yes,less than rm20,...,5,social media;in store displays,yes,0,1,0,0,0,1,1
2,3,male,from 20 to 29,employed,"less than rm25,000",monthly,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,4,in store displays;billboards,yes,1,0,0,0,0,0,0
3,4,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,no,less than rm20,...,3,through friends and word of mouth,no,1,0,0,0,0,0,0
4,5,male,from 20 to 29,student,"less than rm25,000",monthly,take away,between 30 minutes to 1 hour,no,around rm20 - rm40,...,3,starbucks website/apps;social media,yes,1,0,0,0,1,0,1

In [124]:
df['total_purchased'].value_counts()

total_purchased
0    100
1     16
2      5
Name: count, dtype: int64

Count the occurrences of each unique value in the 'annual_income' column

In [125]:
df.annual_income.value_counts()

annual_income
less than rm25,000       70
rm25,000 - rm50,000      25
rm50,000 - rm100,000     17
more than rm150,000       6
rm100,000 - rm150,000     3
Name: count, dtype: int64

Print the unique values in the 'annual_income' column

In [126]:
print(df['annual_income'].unique())

['less than rm25,000' 'rm50,000 - rm100,000' 'rm25,000 - rm50,000'
 'rm100,000 - rm150,000' 'more than rm150,000']

Map income ranges to numeric categories

In [127]:
df['annual_income_encoded'] = df.annual_income.map(
    {
        'less than rm25,000':1,
        'rm25,000 - rm50,000':2,
        'rm50,000 - rm100,000':3,
        'rm100,000 - rm150,000':4,
        'more than rm150,000':5,
    }

)
df.head()

,Customer_ID,gender,age,current_status,annual_income,visit_frequency,enjoy_method,visit_duration,membership_card,spend_per_visit,...,promotion_source,continue_buying,coffee,cold drinks,juices,never,Purchased_Food,Purchased_pastries,total_purchased,annual_income_encoded
0,1,female,from 20 to 29,student,"less than rm25,000",rarely,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,starbucks website/apps;social media;emails;dea...,yes,1,0,0,0,0,0,0,1
1,2,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,yes,less than rm20,...,social media;in store displays,yes,0,1,0,0,0,1,1,1
2,3,male,from 20 to 29,employed,"less than rm25,000",monthly,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,in store displays;billboards,yes,1,0,0,0,0,0,0,1
3,4,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,no,less than rm20,...,through friends and word of mouth,no,1,0,0,0,0,0,0,1
4,5,male,from 20 to 29,student,"less than rm25,000",monthly,take away,between 30 minutes to 1 hour,no,around rm20 - rm40,...,starbucks website/apps;social media,yes,1,0,0,0,1,0,1,1

In [128]:
df.annual_income_encoded.value_counts()

annual_income_encoded
1    70
2    25
3    17
5     6
4     3
Name: count, dtype: int64

In [129]:
df.annual_income_encoded.describe()

count    121.000000
mean       1.760331
std        1.103213
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        5.000000
Name: annual_income_encoded, dtype: float64

we will classify our customers due to thier anual income
we will use the mean

new

In [130]:
def classify_income(income):
    if income ==1:
        return 'low income'
    elif income == 2 :
        return 'middle income'
    else:
      return 'high income'

df['income_category'] = df['annual_income_encoded'].apply(classify_income)
df.income_category.value_counts()

income_category
low income       70
high income      26
middle income    25
Name: count, dtype: int64

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 121 entries, 0 to 121
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            121 non-null    int64
 1   gender                 121 non-null    object
 2   age                    121 non-null    object
 3   current_status         121 non-null    object
 4   annual_income          121 non-null    object
 5   visit_frequency        121 non-null    object
 6   enjoy_method           121 non-null    object
 7   visit_duration         121 non-null    object
 8   membership_card        121 non-null    object
 9   spend_per_visit        121 non-null    object
 10  quality_rating         121 non-null    int64
 11  price_rating           121 non-null    int64
 12  sales_importance       121 non-null    int64
 13  ambiance_rating        121 non-null    int64
 14  service_rating         121 non-null    int64
 15  promotion_source       121 non-null    object
 16  continue_buying        121 non-null    object
 17  coffee                 121 non-null    int64
 18  cold drinks            121 non-null    int64
 19  juices                 121 non-null    int64
 20  never                  121 non-null    int64
 21  Purchased_Food         121 non-null    int64
 22  Purchased_pastries     121 non-null    int64
 23  total_purchased        121 non-null    int64
 24  annual_income_encoded  121 non-null    int64
 25  income_category        121 non-null    object
dtypes: int64(14), object(12)
memory usage: 25.5+ KB

Count the occurrences of each unique value in the 'visit_frequency' column

In [132]:
df.visit_frequency.value_counts()

visit_frequency
rarely     76
monthly    26
weekly      9
never       8
daily       2
Name: count, dtype: int64

دا ليه؟؟
Define a function to classify visitors based on their visit frequency

**Text fett markieren**
Define a function to classify visit duration into categories

new

In [133]:
def classify_duration(duration):
    # Classify as 'Short visit' for durations below 30 minutes
    if any (item in duration.lower() for item in ['below 30 minutes' , 'between 30 minutes to 1 hour']):
        return 'short visit'
    # Classify as 'long visit' for durations between 1 hour to 2 hours
    elif any (item in duration.lower() for item in ['between 1 hour to 2 hours', 'between 2 hours to 3 hours','more than 3 hours']):
        return 'long visit'
   # Default classification for unexpected values
    else:
        return 'no category'

Create a new column 'visit_duration_category' by applying the classify_duration function

In [134]:
df['visit_duration_category'] = df['visit_duration'].apply(classify_duration)

df.head()

,Customer_ID,gender,age,current_status,annual_income,visit_frequency,enjoy_method,visit_duration,membership_card,spend_per_visit,...,coffee,cold drinks,juices,never,Purchased_Food,Purchased_pastries,total_purchased,annual_income_encoded,income_category,visit_duration_category
0,1,female,from 20 to 29,student,"less than rm25,000",rarely,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,1,0,0,0,0,0,0,1,low income,short visit
1,2,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,yes,less than rm20,...,0,1,0,0,0,1,1,1,low income,short visit
2,3,male,from 20 to 29,employed,"less than rm25,000",monthly,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,1,0,0,0,0,0,0,1,low income,short visit
3,4,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,no,less than rm20,...,1,0,0,0,0,0,0,1,low income,short visit
4,5,male,from 20 to 29,student,"less than rm25,000",monthly,take away,between 30 minutes to 1 hour,no,around rm20 - rm40,...,1,0,0,0,1,0,1,1,low income,short visit

Count the occurrences of each unique value in the 'spend_per_visit' column

In [135]:
df.spend_per_visit.value_counts()

spend_per_visit
less than rm20        58
around rm20 - rm40    45
zero                  11
more than rm40         7
Name: count, dtype: int64

new

Classify customers as high spender, medium spender or low spender

In [136]:
def encoding_spend(spending):
    # Classify as 'low spender' for spending below RM 20
    if 'less than rm20' in spending.lower():
        return 1
    # Classify as 'medium spender' for spending between RM 20 and RM 40
    elif 'around rm20 - rm40' in spending.lower():
        return 2
    # Classify as 'high spender' for spending more than RM 40
    elif 'more than rm40' in spending.lower():
        return 3
    # Default classification for unexpected values
    else:
        return 0

Create a new column 'spending_category' by applying the classify_spending function

In [137]:
df['spend_per_visit_encoded'] = df['spend_per_visit'].apply(encoding_spend)

df.head()

,Customer_ID,gender,age,current_status,annual_income,visit_frequency,enjoy_method,visit_duration,membership_card,spend_per_visit,...,cold drinks,juices,never,Purchased_Food,Purchased_pastries,total_purchased,annual_income_encoded,income_category,visit_duration_category,spend_per_visit_encoded
0,1,female,from 20 to 29,student,"less than rm25,000",rarely,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,0,0,0,0,0,0,1,low income,short visit,1
1,2,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,yes,less than rm20,...,1,0,0,0,1,1,1,low income,short visit,1
2,3,male,from 20 to 29,employed,"less than rm25,000",monthly,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,0,0,0,0,0,0,1,low income,short visit,1
3,4,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,no,less than rm20,...,0,0,0,0,0,0,1,low income,short visit,1
4,5,male,from 20 to 29,student,"less than rm25,000",monthly,take away,between 30 minutes to 1 hour,no,around rm20 - rm40,...,0,0,0,1,0,1,1,low income,short visit,2

In [138]:
df['spend_per_visit'].value_counts()

spend_per_visit
less than rm20        58
around rm20 - rm40    45
zero                  11
more than rm40         7
Name: count, dtype: int64

In [139]:
df['spend_per_visit_encoded'].value_counts()

spend_per_visit_encoded
1    58
2    45
0    11
3     7
Name: count, dtype: int64

In [140]:
df['spend_per_visit_encoded'].describe()

count    121.000000
mean       1.396694
std        0.735746
min        0.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        3.000000
Name: spend_per_visit_encoded, dtype: float64

new

as we see the mean to spend is 1.396694
so we classify all of the customers over this value as a high spenders customers

In [141]:
def classify_spending(spending):
    if spending > 1.396694:
        return 'high spender'
    elif spending < 1.396694:
        return 'low spender'

df["spending_catogery"] = df['spend_per_visit_encoded'].apply(classify_spending)
df.spending_catogery.value_counts()

spending_catogery
low spender     69
high spender    52
Name: count, dtype: int64

Define the loyalty calculation function
- The function takes multiple columns ('visitor_type', 'spending_category', 'visit_duration_category', and 'membership_card') as inputs to calculate loyalty levels

Count the occurrences of each unique value in the 'promotion_source' column

In [142]:
df.promotion_source.value_counts()

promotion_source
social media                                                                                                                                   31
social media;through friends and word of mouth                                                                                                 14
through friends and word of mouth                                                                                                               9
starbucks website/apps;social media                                                                                                             9
in store displays                                                                                                                               7
starbucks website/apps;social media;emails;through friends and word of mouth                                                                    6
starbucks website/apps;social media;through friends and word of mouth                                                                           6
starbucks website/apps                                                                                                                          6
social media;through friends and word of mouth;in store displays;billboards                                                                     3
social media;in store displays                                                                                                                  3
social media;emails                                                                                                                             3
starbucks website/apps;emails                                                                                                                   2
social media;through friends and word of mouth;billboards                                                                                       2
emails                                                                                                                                          2
social media;through friends and word of mouth;in store displays                                                                                2
social media;deal sites (fave, iprice, etc...)                                                                                                  1
never hear                                                                                                                                      1
social media;emails;through friends and word of mouth                                                                                           1
billboards                                                                                                                                      1
social media;deal sites (fave, iprice, etc...);through friends and word of mouth                                                                1
starbucks website/apps;deal sites (fave, iprice, etc...)                                                                                        1
starbucks website/apps;social media;emails;deal sites (fave, iprice, etc...)                                                                    1
application offer                                                                                                                               1
starbucks website/apps;social media;deal sites (fave, iprice, etc...);through friends and word of mouth                                         1
social media;emails;deal sites (fave, iprice, etc...);through friends and word of mouth;in store displays;billboards                            1
starbucks website/apps;social media;emails;billboards                                                                                           1
starbucks website/apps;social media;through friends and word of mouth;in store displays                                                         1
social media;in store displays;billboards                                                                                                       1
through friends and word of mouth;in store displays                                                                                             1
in store displays;billboards                                                                                                                    1
starbucks website/apps;social media;emails;deal sites (fave, iprice, etc...);through friends and word of mouth;in store displays;billboards     1
Name: count, dtype: int64

- Splitting the composite attributes into lists
- Here, I'm splitting the 'promotion_source' column into separate items using the delimiter ';'.
- This will allow me to work with each individual item separately.

In [143]:
split_items = df['promotion_source'].str.split(';')
print("\n Split 'promotion_source' into lists:")
split_items.head()

 Split 'promotion_source' into lists:

0    [starbucks website/apps, social media, emails,...
1                    [social media, in store displays]
2                      [in store displays, billboards]
3                  [through friends and word of mouth]
4               [starbucks website/apps, social media]
Name: promotion_source, dtype: object

- Extracting unique items from the lists
- To create individual columns for each item, I first need to find all unique items in the 'promotion_source' data.
- I initialize an empty list called unique_items and populate it by iterating through each list in split_items.
- If an item is not already in unique_items, I add it. This ensures no duplicates in the final list.

In [144]:
unique_items = []
for sublist in split_items:
    for item in sublist:
        if item not in unique_items:
            unique_items.append(item)

print("\n Unique items extracted from 'promotion_source':")
print(unique_items)

 Unique items extracted from 'promotion_source':
['starbucks website/apps', 'social media', 'emails', 'deal sites (fave, iprice, etc...)', 'in store displays', 'billboards', 'through friends and word of mouth', 'application offer', 'never hear']

- Creating new columns for each unique item
- Now that I have all unique items, I create a new column for each one in the DataFrame.
- 1. For each unique item, I check if it exists in the 'promotion_source' column for a given row.
- 2. If the item exists, I assign a value of 1 to the new column; otherwise, I assign 0.

In [145]:
for item in unique_items:
    df[item] = df['promotion_source'].apply(lambda x: 1 if item in x else 0)

df.drop(columns=['promotion_source'],inplace=True)
print("\n DataFrame with new columns for each unique item:")
df.head()

 DataFrame with new columns for each unique item:

,Customer_ID,gender,age,current_status,annual_income,visit_frequency,enjoy_method,visit_duration,membership_card,spend_per_visit,...,spending_catogery,starbucks website/apps,social media,emails,"deal sites (fave, iprice, etc...)",in store displays,billboards,through friends and word of mouth,application offer,never hear
0,1,female,from 20 to 29,student,"less than rm25,000",rarely,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,low spender,1,1,1,1,0,0,0,0,0
1,2,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,yes,less than rm20,...,low spender,0,1,0,0,1,0,0,0,0
2,3,male,from 20 to 29,employed,"less than rm25,000",monthly,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,low spender,0,0,0,0,1,1,0,0,0
3,4,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,no,less than rm20,...,low spender,0,0,0,0,0,0,1,0,0
4,5,male,from 20 to 29,student,"less than rm25,000",monthly,take away,between 30 minutes to 1 hour,no,around rm20 - rm40,...,high spender,1,1,0,0,0,0,0,0,0

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 121 entries, 0 to 121
Data columns (total 37 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer_ID                        121 non-null    int64
 1   gender                             121 non-null    object
 2   age                                121 non-null    object
 3   current_status                     121 non-null    object
 4   annual_income                      121 non-null    object
 5   visit_frequency                    121 non-null    object
 6   enjoy_method                       121 non-null    object
 7   visit_duration                     121 non-null    object
 8   membership_card                    121 non-null    object
 9   spend_per_visit                    121 non-null    object
 10  quality_rating                     121 non-null    int64
 11  price_rating                       121 non-null    int64
 12  sales_importance                   121 non-null    int64
 13  ambiance_rating                    121 non-null    int64
 14  service_rating                     121 non-null    int64
 15  continue_buying                    121 non-null    object
 16  coffee                             121 non-null    int64
 17  cold drinks                        121 non-null    int64
 18  juices                             121 non-null    int64
 19  never                              121 non-null    int64
 20  Purchased_Food                     121 non-null    int64
 21  Purchased_pastries                 121 non-null    int64
 22  total_purchased                    121 non-null    int64
 23  annual_income_encoded              121 non-null    int64
 24  income_category                    121 non-null    object
 25  visit_duration_category            121 non-null    object
 26  spend_per_visit_encoded            121 non-null    int64
 27  spending_catogery                  121 non-null    object
 28  starbucks website/apps             121 non-null    int64
 29  social media                       121 non-null    int64
 30  emails                             121 non-null    int64
 31  deal sites (fave, iprice, etc...)  121 non-null    int64
 32  in store displays                  121 non-null    int64
 33  billboards                         121 non-null    int64
 34  through friends and word of mouth  121 non-null    int64
 35  application offer                  121 non-null    int64
 36  never hear                         121 non-null    int64
dtypes: int64(24), object(13)
memory usage: 35.9+ KB

In [147]:
df['digtal_marketing'] = df['starbucks website/apps'] | df['social media'] | df['emails'] | df['deal sites (fave, iprice, etc...)']
df['traditional_marketing'] = df['in store displays'] | df['billboards']

Define a function to classify promotion sources based on sources

Drop the original promotion source columns

In [148]:
columns_to_drop = [
    'starbucks website/apps', 'social media', 'emails',
    'deal sites (fave, iprice, etc...)', 'in store displays',
    'billboards',
    'application offer'
]
df.drop(columns=columns_to_drop, inplace=True)

df.head()

,Customer_ID,gender,age,current_status,annual_income,visit_frequency,enjoy_method,visit_duration,membership_card,spend_per_visit,...,total_purchased,annual_income_encoded,income_category,visit_duration_category,spend_per_visit_encoded,spending_catogery,through friends and word of mouth,never hear,digtal_marketing,traditional_marketing
0,1,female,from 20 to 29,student,"less than rm25,000",rarely,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,0,1,low income,short visit,1,low spender,0,0,1,0
1,2,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,yes,less than rm20,...,1,1,low income,short visit,1,low spender,0,0,1,1
2,3,male,from 20 to 29,employed,"less than rm25,000",monthly,dine in,between 30 minutes to 1 hour,yes,less than rm20,...,0,1,low income,short visit,1,low spender,0,0,0,1
3,4,female,from 20 to 29,student,"less than rm25,000",rarely,take away,below 30 minutes,no,less than rm20,...,0,1,low income,short visit,1,low spender,1,0,0,0
4,5,male,from 20 to 29,student,"less than rm25,000",monthly,take away,between 30 minutes to 1 hour,no,around rm20 - rm40,...,1,1,low income,short visit,2,high spender,0,0,1,0

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 121 entries, 0 to 121
Data columns (total 32 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer_ID                        121 non-null    int64
 1   gender                             121 non-null    object
 2   age                                121 non-null    object
 3   current_status                     121 non-null    object
 4   annual_income                      121 non-null    object
 5   visit_frequency                    121 non-null    object
 6   enjoy_method                       121 non-null    object
 7   visit_duration                     121 non-null    object
 8   membership_card                    121 non-null    object
 9   spend_per_visit                    121 non-null    object
 10  quality_rating                     121 non-null    int64
 11  price_rating                       121 non-null    int64
 12  sales_importance                   121 non-null    int64
 13  ambiance_rating                    121 non-null    int64
 14  service_rating                     121 non-null    int64
 15  continue_buying                    121 non-null    object
 16  coffee                             121 non-null    int64
 17  cold drinks                        121 non-null    int64
 18  juices                             121 non-null    int64
 19  never                              121 non-null    int64
 20  Purchased_Food                     121 non-null    int64
 21  Purchased_pastries                 121 non-null    int64
 22  total_purchased                    121 non-null    int64
 23  annual_income_encoded              121 non-null    int64
 24  income_category                    121 non-null    object
 25  visit_duration_category            121 non-null    object
 26  spend_per_visit_encoded            121 non-null    int64
 27  spending_catogery                  121 non-null    object
 28  through friends and word of mouth  121 non-null    int64
 29  never hear                         121 non-null    int64
 30  digtal_marketing                   121 non-null    int64
 31  traditional_marketing              121 non-null    int64
dtypes: int64(19), object(13)
memory usage: 31.2+ KB

Identify the most successful category based on customer loyalty
ممكن نشوفهم مع كل الزباين مش مع الhigh بس

In [150]:
# Group the data by 'promotion_source' and 'loyalty' to calculate counts for each category
promotion_loyalty_counts = df.groupby(['promotion_category', 'loyalty']).size().unstack(fill_value=0)
print(promotion_loyalty_counts)
# Add a new column for the total count of all loyalty levels for each promotion source
promotion_loyalty_counts['total_loyalty_count'] = promotion_loyalty_counts.sum(axis=1)

# Add a new column for the percentage of 'high loyalty' for each promotion source
promotion_loyalty_counts['high_loyalty_percent'] = (
    promotion_loyalty_counts.get('high loyalty', 0) / promotion_loyalty_counts['total_loyalty_count']
) * 100

# Reset the index to include the 'promotion_source' as a column in the resulting DataFrame
promotion_loyalty_counts = promotion_loyalty_counts.reset_index()

# Display the updated DataFrame with the new columns
print(promotion_loyalty_counts)

KeyError: 'promotion_category'

In [ ]:
df.info()

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.describe()